CREATE VIEW AUX_DATOS_VALORES_PIVOT AS (
SELECT COD_VALOR,
       FECHA,
       APERTURA,
       MAXIMO,
       MINIMO,
       CIERRE,
       VOLUMEN,
       ((CIERRE + MAXIMO + MINIMO) / 3) AS PIVOT
  FROM DATOS_VALORES
);

CREATE VIEW AUX_DATOS_TECNIVOS_VALORES AS (
SELECT COD_VALOR,
       FECHA,
       APERTURA,
       MAXIMO,
       MINIMO,
       CIERRE,
       VOLUMEN,
       PIVOT,
       ((PIVOT * 2) - MINIMO) AS R1,
       ((PIVOT * 2) - MAXIMO) AS S1
  FROM AUX_DATOS_VALORES_PIVOT
);

CREATE VIEW DATOS_TECNIVOS_VALORES AS (
SELECT COD_VALOR,
       FECHA,
       APERTURA,
       MAXIMO,
       MINIMO,
       CIERRE,
       VOLUMEN,
       PIVOT,
       R1,
       S1,
       (PIVOT - S1 + R1) AS R2,
       (PIVOT - R1 + S1) AS S2
  FROM AUX_DATOS_VALORES_PIVOT
);